// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxlcoaxlybmknwcysdhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bGNvYXhseWJta253Y3lzZGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MzYwOTMsImV4cCI6MjA1NjUxMjA5M30.1IqfnflE3wtsDoWitvdMc__RwjAqisMrAOyIvFy9seM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);